import type { ComponentType, SVGProps } from "react";
import type { CatalogItem, CategoryKey } from "@/lib/catalog";
import { StoreIcon } from "@/components/icons";
import {
  FoodAardappel,
  FoodAardbei,
  FoodAppel,
  FoodAsperge,
  FoodBier,
  FoodBloem,
  FoodBoerenkool,
  FoodBoter,
  FoodBrood,
  FoodCourgette,
  FoodEi,
  FoodFramboos,
  FoodFruitMand,
  FoodGeitenkaas,
  FoodGroenteMand,
  FoodHoning,
  FoodIjs,
  FoodJam,
  FoodKaas,
  FoodKers,
  FoodKip,
  FoodKwark,
  FoodLam,
  FoodMelk,
  FoodNoot,
  FoodPeer,
  FoodPompoen,
  FoodRabarber,
  FoodRadijs,
  FoodRund,
  FoodSap,
  FoodSpruiten,
  FoodStamppot,
  FoodStoofpeer,
  FoodTomaat,
  FoodVarken,
  FoodWijn,
  FoodWorst,
  FoodWortel,
  FoodYoghurt,
  FoodKarnemelk,
  FoodSlagroom,
  FoodVla,
  FoodSpek,
  FoodSla,
  FoodKomkommer,
  FoodPaprika,
  FoodUi,
  FoodKnoflook,
  FoodPrei,
  FoodBroccoli,
  FoodBloemkool,
  FoodBiet,
  FoodSperzieboon,
  FoodPaddenstoel,
  FoodKruiden,
  FoodPlant,
  FoodDruiven,
  FoodBes,
  FoodBraam,
  FoodPruim,
  FoodMeloen,
  FoodCroissant,
  FoodStokbrood,
  FoodTaart,
  FoodKoek,
  FoodMeel,
  FoodKastanje,
  FoodMosterd,
  FoodStroop,
  FoodCider,
  FoodVis,
  FoodPaling,
  FoodForel,
  FoodGeit,
  FoodKefir,
  FoodBrie,
  FoodBlauweKaas,
  FoodEend,
  FoodKalkoen,
  FoodHamburger,
  FoodSaucijs,
  FoodSalami,
  FoodSpinazie,
  FoodAndijvie,
  FoodWitlof,
  FoodRodeKool,
  FoodSpitskool,
  FoodSnijboon,
  FoodDoperwt,
  FoodTuinboon,
  FoodMais,
  FoodPastinaak,
  FoodKnolselderij,
  FoodSnoeptomaat,
  FoodBlauweBes,
  FoodKruisbes,
  FoodVolkoren,
  FoodSpelt,
  FoodRogge,
  FoodKrentenbrood,
  FoodOntbijtkoek,
  FoodAppeltaart,
  FoodStroopwafel,
  FoodHoningraat,
  FoodChocolade,
  FoodAppelsap,
  FoodPerensap,
  FoodSiroop,
  FoodThee,
  FoodKoffie,
  FoodOlie,
  FoodAzijn,
  FoodPesto,
  FoodSoep,
  FoodZuurkool,
  FoodHazelnoot,
  FoodWalnoot,
  FoodAmandel,
  FoodCashewnoot,
  FoodPinda,
  FoodZonnebloempit,
  FoodPompoenpit,
  FoodLijnzaad,
  FoodChiazaad,
  FoodSesamzaad,
  FoodPasta,
  FoodRijst,
  FoodWcPapier,
  FoodSchoonmaak,
  FoodLuier,
  FoodTandpasta,
  FoodShampoo,
  FoodZeep,
  FoodWasmiddel,
  FoodVuilniszak,
  FoodKeukenrol,
  FoodSuiker,
  FoodZout,
  FoodPeper,
  FoodPindakaas,
  FoodHagelslag,
  FoodChips,
  FoodMuesli,
  FoodWater,
  FoodFrisdrank,
} from "@/components/food-icons";

type Icon = ComponentType<SVGProps<SVGSVGElement>>;

// Elk catalogusitem zijn eigen, onderscheidend icoon
const ITEM_ICONS: Record<string, Icon> = {
  melk: FoodMelk,
  yoghurt: FoodYoghurt,
  kwark: FoodKwark,
  boter: FoodBoter,
  ijs: FoodIjs,
  eieren: FoodEi,
  kaas: FoodKaas,
  geitenkaas: FoodGeitenkaas,
  rundvlees: FoodRund,
  varkensvlees: FoodVarken,
  kip: FoodKip,
  worst: FoodWorst,
  lamsvlees: FoodLam,
  groente: FoodGroenteMand,
  tomaten: FoodTomaat,
  asperges: FoodAsperge,
  pompoen: FoodPompoen,
  courgette: FoodCourgette,
  boerenkool: FoodBoerenkool,
  spruiten: FoodSpruiten,
  winterpeen: FoodWortel,
  radijs: FoodRadijs,
  stamppotgroente: FoodStamppot,
  rabarber: FoodRabarber,
  fruit: FoodFruitMand,
  aardbeien: FoodAardbei,
  appels: FoodAppel,
  peren: FoodPeer,
  kersen: FoodKers,
  frambozen: FoodFramboos,
  stoofperen: FoodStoofpeer,
  aardappelen: FoodAardappel,
  vis: FoodVis,
  brood: FoodBrood,
  honing: FoodHoning,
  jam: FoodJam,
  sap: FoodSap,
  bier: FoodBier,
  wijn: FoodWijn,
  noten: FoodNoot,
  bloemen: FoodBloem,
  karnemelk: FoodKarnemelk,
  slagroom: FoodSlagroom,
  vla: FoodVla,
  gehakt: FoodRund,
  spek: FoodSpek,
  sla: FoodSla,
  komkommer: FoodKomkommer,
  paprika: FoodPaprika,
  ui: FoodUi,
  knoflook: FoodKnoflook,
  prei: FoodPrei,
  broccoli: FoodBroccoli,
  bloemkool: FoodBloemkool,
  bieten: FoodBiet,
  sperziebonen: FoodSperzieboon,
  paddenstoelen: FoodPaddenstoel,
  kruiden: FoodKruiden,
  moestuinplantjes: FoodPlant,
  druiven: FoodDruiven,
  bessen: FoodBes,
  bramen: FoodBraam,
  pruimen: FoodPruim,
  meloen: FoodMeloen,
  croissant: FoodCroissant,
  stokbrood: FoodStokbrood,
  taart: FoodTaart,
  koekjes: FoodKoek,
  appelstroop: FoodStroop,
  cider: FoodCider,
  kastanjes: FoodKastanje,
  meel: FoodMeel,
  mosterd: FoodMosterd,
  geitenzuivel: FoodGeit,
  kefir: FoodKefir,
  brie: FoodBrie,
  blauwekaas: FoodBlauweKaas,
  eend: FoodEend,
  kalkoen: FoodKalkoen,
  hamburgers: FoodHamburger,
  saucijzen: FoodSaucijs,
  drogeworst: FoodSalami,
  spinazie: FoodSpinazie,
  andijvie: FoodAndijvie,
  witlof: FoodWitlof,
  rodekool: FoodRodeKool,
  spitskool: FoodSpitskool,
  snijbonen: FoodSnijboon,
  doperwten: FoodDoperwt,
  tuinbonen: FoodTuinboon,
  mais: FoodMais,
  pastinaak: FoodPastinaak,
  knolselderij: FoodKnolselderij,
  snoeptomaatjes: FoodSnoeptomaat,
  blauwebessen: FoodBlauweBes,
  kruisbessen: FoodKruisbes,
  forel: FoodForel,
  paling: FoodPaling,
  zalmforel: FoodVis,
  volkorenbrood: FoodVolkoren,
  speltbrood: FoodSpelt,
  roggebrood: FoodRogge,
  krentenbrood: FoodKrentenbrood,
  ontbijtkoek: FoodOntbijtkoek,
  appeltaart: FoodAppeltaart,
  stroopwafels: FoodStroopwafel,
  honingraat: FoodHoningraat,
  chocolade: FoodChocolade,
  appelsap: FoodAppelsap,
  perensap: FoodPerensap,
  siroop: FoodSiroop,
  kruidenthee: FoodThee,
  koffie: FoodKoffie,
  koolzaadolie: FoodOlie,
  azijn: FoodAzijn,
  pesto: FoodPesto,
  soep: FoodSoep,
  zuurkool: FoodZuurkool,
  hazelnoten: FoodHazelnoot,
  walnoten: FoodWalnoot,
  amandelen: FoodAmandel,
  cashewnoten: FoodCashewnoot,
  pinda: FoodPinda,
  zonnebloempitten: FoodZonnebloempit,
  pompoenpitten: FoodPompoenpit,
  lijnzaad: FoodLijnzaad,
  chiazaad: FoodChiazaad,
  sesamzaad: FoodSesamzaad,
  pasta: FoodPasta,
  rijst: FoodRijst,
  muesli: FoodMuesli,
  suiker: FoodSuiker,
  zout: FoodZout,
  peper: FoodPeper,
  pindakaas: FoodPindakaas,
  hagelslag: FoodHagelslag,
  chips: FoodChips,
  water: FoodWater,
  frisdrank: FoodFrisdrank,
  wcpapier: FoodWcPapier,
  keukenrol: FoodKeukenrol,
  schoonmaak: FoodSchoonmaak,
  wasmiddel: FoodWasmiddel,
  vuilniszakken: FoodVuilniszak,
  zeep: FoodZeep,
  shampoo: FoodShampoo,
  tandpasta: FoodTandpasta,
  luiers: FoodLuier,
};

const CATEGORY_ICONS: Record<CategoryKey, Icon> = {
  zuivel: FoodMelk,
  eieren: FoodEi,
  kaas: FoodKaas,
  vlees: FoodWorst,
  groente: FoodWortel,
  fruit: FoodAppel,
  aardappelen: FoodAardappel,
  vis: FoodVis,
  brood: FoodBrood,
  zoet: FoodHoning,
  dranken: FoodBier,
  overig: StoreIcon,
  supermarkt: StoreIcon,
};

// Tint per categorie: tegels krijgen een eigen achtergrond en icoonkleur
// binnen de drie kleurfamilies — dat maakt de tegelwand leesbaar zoals Bring.
const CATEGORY_TINTS: Record<CategoryKey, { tileBg: string; icon: string }> = {
  zuivel: { tileBg: "bg-cream-100", icon: "text-terra-400" },
  eieren: { tileBg: "bg-terra-50", icon: "text-terra-500" },
  kaas: { tileBg: "bg-cream-200", icon: "text-terra-500" },
  vlees: { tileBg: "bg-terra-100", icon: "text-terra-700" },
  groente: { tileBg: "bg-terra-50", icon: "text-terra-600" },
  fruit: { tileBg: "bg-terra-100", icon: "text-terra-500" },
  aardappelen: { tileBg: "bg-cream-200", icon: "text-terra-600" },
  vis: { tileBg: "bg-cream-100", icon: "text-terra-500" },
  brood: { tileBg: "bg-cream-100", icon: "text-terra-600" },
  zoet: { tileBg: "bg-terra-50", icon: "text-terra-500" },
  dranken: { tileBg: "bg-terra-100", icon: "text-terra-600" },
  overig: { tileBg: "bg-cream-100", icon: "text-ink-500" },
  supermarkt: { tileBg: "bg-cream-200", icon: "text-ink-500" },
};

export function iconForItem(item: Pick<CatalogItem, "key" | "category">): Icon {
  return ITEM_ICONS[item.key] ?? CATEGORY_ICONS[item.category];
}

export function iconForCategory(key: CategoryKey): Icon {
  return CATEGORY_ICONS[key];
}

export function tintForCategory(key: CategoryKey): { tileBg: string; icon: string } {
  return CATEGORY_TINTS[key];
}
